name: "my-website"
output_dir: "_site"
navbar:
  title: "My Website"
  left:
    - text: "Notebook"
      icon: fa-home
      href: rMarkdown_notebook.nb.html
    - text: "rmd_Document"
      icon: fa-info
      href: rMarkdown_doc.html
    - text: "More"
      icon: fa-gear
      menu:
        - text: "Heading 1"
        - text: "Simple html page"
          href: R_HTML_document.html
        - text: "Page B"
          href: page_b.html
        - text: "---------"
        - text: "Heading 2"
        - text: "Page C"
          href: page_c.html
        - text: "Page D"
          href: page_d.html
  right:
    - icon: fa-question fa-lg
      href: https://example.com
